CREATE DATABASE [ClinicPezeshki]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClinicMilad', FILENAME = N'C:\MSSQLDATA\ClinicMilad.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ClinicMilad_log', FILENAME = N'C:\MSSQLDATA\ClinicMilad_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ClinicPezeshki] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClinicPezeshki].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ClinicPezeshki] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET ARITHABORT OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ClinicPezeshki] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ClinicPezeshki] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ClinicPezeshki] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ClinicPezeshki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ClinicPezeshki] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ClinicPezeshki] SET  MULTI_USER 
GO
ALTER DATABASE [ClinicPezeshki] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ClinicPezeshki] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ClinicPezeshki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ClinicPezeshki] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ClinicPezeshki] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ClinicPezeshki] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ClinicPezeshki] SET QUERY_STORE = ON
GO
ALTER DATABASE [ClinicPezeshki] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ClinicPezeshki]
GO
/****** Object:  Table [dbo].[Patients]    Script Date: 09/06/2025 19:51:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patients](
	[PatientID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[BirthDate] [nvarchar](50) NULL,
	[PhoneNumber] [nvarchar](20) NULL,
	[Address] [nvarchar](255) NULL,
 CONSTRAINT [PK__Patients__970EC34668226AC5] PRIMARY KEY CLUSTERED 
(
	[PatientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Prescriptions]    Script Date: 09/06/2025 19:51:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prescriptions](
	[PrescriptionID] [int] IDENTITY(1,1) NOT NULL,
	[PatientID] [int] NULL,
	[DoctorID] [int] NULL,
	[PrescriptionText] [nvarchar](max) NULL,
	[DateCreated] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PrescriptionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 09/06/2025 19:51:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Role] [nvarchar](20) NOT NULL,
	[FullName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK__Users__1788CCAC93BB0C27] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Prescriptions] ADD  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [dbo].[Prescriptions]  WITH CHECK ADD  CONSTRAINT [FK__Prescript__Docto__3C69FB99] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Prescriptions] CHECK CONSTRAINT [FK__Prescript__Docto__3C69FB99]
GO
ALTER TABLE [dbo].[Prescriptions]  WITH CHECK ADD  CONSTRAINT [FK__Prescript__Patie__3B75D760] FOREIGN KEY([PatientID])
REFERENCES [dbo].[Patients] ([PatientID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Prescriptions] CHECK CONSTRAINT [FK__Prescript__Patie__3B75D760]
GO
USE [master]
GO
ALTER DATABASE [ClinicPezeshki] SET  READ_WRITE 
GO
